import Head from 'next/head'
import Avatar from '../components/Avatar'
import {MicrophoneIcon, ViewGridIcon, MenuAlt1Icon} from "@heroicons/react/solid"
import {SearchIcon} from "@heroicons/react/outline"
import {useRef} from 'react'
import {useRouter} from 'next/router'
import Image from 'next/image'
import Footer from '../components/Footer'

export default function Home() {
  const text = useRef(null)
  const router = useRouter()


  const search = e => {
    e.preventDefault()
    const term = text.current.value;
    console.log(term)
    if(!term) {
      return;
    }

    router.push(`./search?term=${term}`)


  }
  return (
    <div className="flex flex-col items-center h-screen justify-between">
      <Head>
        <title>Google Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        {/* Header */}
        <header className="flex w-full p-5 justify-between text-sm text-gray-700">
        {/* Left */}
          <div className="flex space-x-4 items-center">
            <MenuAlt1Icon className="h-5 text-gray-500"/>
            <p className="link">About</p>
            <p className="link">Store</p>
          </div>
        {/* Right */}
          <div className="flex space-x-4 items-center">
            <p className="link">Gmail</p>
            <p className="link">Images</p>
            {/* Icon */}
            <ViewGridIcon className="h-10  rounded-full hover:bg-gray-100 p-2 cursor-pointer"/>
            {/* Avatar */}
            <Avatar url='https://coaching.papareact.com/ai9'/>
          </div>
        </header>
        {/* Body */}
        <form className="flex flex-col items-center mt-30 p-2 w-4/5">
          <Image src='https://www.google.co.uk/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png' height={100} width={300}/>
          <div className="flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg max-w-md rounded-full border border-gray-200 px-5 py-3 items-center sm:max-w-lg lg:max-w-2xl">
            <SearchIcon className="h-5 mr-3 text-gray-500"/>
            <input ref={text} type="" className="flex-grow focus:outline-none rounded-md" />
            <MicrophoneIcon className="h-5 text-gray-500" />
          </div>
          <div className="flex flex-col mt-5  w-1/2 justify-center space-y-2 sm:flex-row sm:space-x-4">
            <button onClick={search} className="center-btn">Google Search</button>
            <button onClick={search} className="center-btn">Im Feeling Lucky</button>
          </div>
        </form>
        {/* footer */}
        <Footer />
    </div>
  )
}
